### ISSUE TITLE
AI Kills Sending in Chat

### ISSUE THREAD

**Issue by Aevoaa** [Desa2k/RecruitAi#1]
When having an AI as say Commander in a Tank, when they kill an DMS Mission AI the Kill gets sent in the chat like a Player Kill:
https://imgur.com/pU1tGFh

**Comment by Desa2k** [comment]
in fn_paraLandSafe.sqf
change "join" to "joinSilent" on lines 59 and 63, for no radio messages. 
Please use my discord for issues, or questions. I wont check here often.

**Comment by Desa2k** [comment]
in fn_paraLandSafe.sqf
change "join" to "joinSilent" on lines 59 and 63, for no radio messages.
Please use my discord for issues, or questions. I wont check here often.
